<?php

namespace MelodyWen\LaravelDevelopment\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

class Column extends Model
{
    public $table = 'information_schema.COLUMNS';

    public $guarded = [];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::addGlobalScope('databases', function (Builder $builder) {

            $builder->whereIn('TABLE_SCHEMA', config('development.database_schema'));
        });
    }
}
