<?php

namespace MelodyWen\LaravelDevelopment\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

class Module extends Model
{
    public $table = 'database_collections';

    public $guarded = [];

    const TYPE = 1;

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::addGlobalScope('type', function (Builder $builder) {
            $builder->where('type', self::TYPE);
        });

        static::saving(function ($model) {
            $model->type = self::TYPE;
        });
    }

    public function table_collections()
    {
        return $this->hasMany(TableCollection::class, 'father_id');
    }
}
