<?php

namespace MelodyWen\LaravelDevelopment\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

class Table extends Model
{
    public $table = 'information_schema.TABLES';

    public $guarded = [];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::addGlobalScope('databases', function (Builder $builder) {

            $builder->whereIn('TABLE_SCHEMA', config('development.database_schema'));
        });
    }

    public function table_collection()
    {
        return $this->hasOne(TableCollection::class, 'module_name', 'TABLE_NAME');
    }
}
